### PR TITLE
updated tfidf

### PR DESCRIPTION
**Pull request by nbalepur**

### CODE REVIEW

**Review by Nonameentered — CHANGES_REQUESTED** [review]
Any reason why we have the /env file added here?

**Comment by nbalepur** [comment]
> Any reason why we have the /env file added here?

Not sure, my computer has been doing this weird thing where it converts the `.env` file to an `env` file, but this can be removed

**Review by Nonameentered — CHANGES_REQUESTED** [review]
Sorry could you actually also add the train code for this into this repo? Would be useful to have in here to centralize it.

**Comment by nbalepur** [comment]
> Sorry could you actually also add the train code for this into this repo? Would be useful to have in here to centralize it.

Added to the `/data` folder!

**Pull request merged**
